export default {
    COLORS: {

        //GENERAL
        GLOBAL_BACKGROUND: "#1C1B1E",
        TITLES_AND_BUTTONS_AND_STARS_COLOR: "#FF859B",
        TEXT_BUTTON: "#312E38",
        SUBTITLES_COLOR: "#FF859B",
        FONTS_COLOR: "#F4EDE8",
        INPUTS_BACKGROUND: "#262529",
        PLACEHOLDERS_COLOR: "#948F99",

        //HEADER
        HEADER_BACKGROUND: "#38373C",
        H1_FONT_COLOR:"#FF859B",
        MAIN_HEADER_FONT_COLOR: "#F4EDE8",
        SECONDARY_HEADER_FONT_COLOR: "#948F99",

        //PAGE HOME
        COMMENTS_FONT_COLOR: "#999591",
        COMMENT_TAGS_BACKGROUND: "#312E38",
        COMMENTS_BACKGROUND: "#403B3C",
        
        //PAGE CREATE MOVIE
        TAGS_BAR_COLOR: "#0D0C0F"


    }
}